apiVersion: v1
kind: Service
metadata:
  name: apachewebsite-service
spec:
  selector:
    app: apachewebsite
  ports:
    - protocol: TCP
      port: 80        # Service port
      targetPort: 80  # Container port
      nodePort: 30080 # Optional: fixed NodePort
  type: NodePort      # Change to LoadBalancer if using cloud provider
